// Generate a journal large enough for the speed gate to mean something.
//
//   node gen-fixture.mjs <transactions> > large.journal
//
// Deliberately varied: several accounts, a currency, and dates spread across
// years, so the parser and the balance report do realistic work rather than
// hitting the same fast path repeatedly.

const count = Number(process.argv[2] ?? 1000);

const expenses = [
  "expenses:food:groceries",
  "expenses:food:dining",
  "expenses:transport:fuel",
  "expenses:transport:transit",
  "expenses:housing:rent",
  "expenses:housing:utilities",
  "expenses:health",
  "expenses:leisure",
];
const assets = ["assets:bank:checking", "assets:bank:savings", "assets:cash"];
const payees = ["market", "cafe", "landlord", "utility co", "pharmacy", "cinema", "station"];

const lines = [];
lines.push("; generated by gen-fixture.mjs - do not edit");
lines.push("");
lines.push("2020-01-01 opening balance");
lines.push("    assets:bank:checking     $100000.00");
lines.push("    equity:opening");
lines.push("");

const start = Date.UTC(2020, 0, 2);
for (let i = 0; i < count; i++) {
  const day = new Date(start + i * 86400000 * 0.7);
  const date = day.toISOString().slice(0, 10);
  const expense = expenses[i % expenses.length];
  const asset = assets[i % assets.length];
  const payee = payees[i % payees.length];
  const amount = (((i * 37) % 20000) / 100 + 1.5).toFixed(2);
  lines.push(`${date} ${payee}`);
  lines.push(`    ${expense}    $${amount}`);
  lines.push(`    ${asset}`);
  lines.push("");
}

process.stdout.write(lines.join("\n"));
